# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: '1 - Build TOTEM with dongle'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_dongle","totem_left","totem_right"]'